name: Build Commit

on:
  push:
    branches:
      - main

permissions:
  packages: write

env:
  IMAGE_TITLE: "dashboard"
  IMAGE_FOLDER: "dashboard"
  IMAGE_PLATFORMS: |
    linux/amd64
    linux/arm64

jobs:
  build_and_push_image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install QEMU
        uses: docker/setup-qemu-action@v2

      - name: Install Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate Image Tags/Labels
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            ghcr.io/${{ github.repository_owner }}/ci/${{ env.IMAGE_TITLE }}
          flavor: |
            latest=false
          tags: |
            type=sha,priority=200,prefix=sha-,format=short
            type=sha,priority=100,prefix=sha-,format=long

      - name: Build and Push Image
        uses: docker/build-push-action@v4
        with:
          context: ./${{ env.IMAGE_FOLDER }}
          push: true
          platforms: ${{ env.IMAGE_PLATFORMS }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=registry,ref=ghcr.io/${{ github.repository_owner }}/ci/${{ inputs.IMAGE_TITLE }}
          cache-to: type=registry,ref=ghcr.io/${{ github.repository_owner }}/ci/${{ env.IMAGE_TITLE }},mode=max